name: Stock Analyzer Bot

on:
  schedule:
    - cron: "0 23 * * 1-5"  # Runs at 10 AM ET Mon-Fri
  workflow_dispatch:       # Allow manual runs

jobs:
  run-stock-check:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
      GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stock analysis script
        run: python main.py
